---
global:
  scrape_interval: 5s  # how often to scrape targets

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['infra-prometheus:9090']

  # Scrape OpenTelemetry Collector (Prometheus exporter)
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']
